# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 03:42
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170110_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_auth',
            field=models.CharField(default=True, max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
